apiVersion: apps/v1
kind: Deployment
metadata:
  name: minty-bot-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minty-v2
  template:
    metadata:
      labels:
        app: minty-v2
    spec:
      containers:
      - name: commander
        image: minty-bot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_RUN_HOST    # <--- Add this section
          value: "0.0.0.0"
        envFrom:
        - secretRef:
            name: minty-secrets
