apiVersion: apps/v1
kind: Deployment
metadata:
  name: minty-bot-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minty-v2
  template:
    metadata:
      labels:
        app: minty-v2
    spec:
      containers:
      - name: commander
        image: minty-bot:latest        # Change from the IP address to this
        imagePullPolicy: IfNotPresent  # Tell K8s: "If you have it locally, use it"
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: minty-secrets        # This links to your bot secrets
