apiVersion: v1
kind: Service
metadata:
  name: minty-service
spec:
  type: NodePort
  selector:
    app: minty-v2        # This MUST match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80           # The port you'll use in the browser
      targetPort: 5005   # The port the app is listening on
      nodePort: 30085    # You can pick a number between 30000-32767
